analytics: {}
color:
  brandColors:
    - '#fffcad'
    - '#6a1395'
    - '#9b609d'
    - '#d3b7a6'
    - '#ff00ff'
  brandStrength: 0
  lightness: 0.6875
  rhythmicContrast: 0.75
  saturation: 0.75
cta: {}
layout_spectrum: 0.76848
name: Random Shit From The Internet
opengraph: {}
purpose: []
typography_spectrum: 0.20576
