name: Random Shit From The Internet
favicon: null
layout_spectrum: 0.14035
typography_spectrum: 0.85088
style: taylor
title: Random Shit From The Internet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - "#355c5b"
    - "#202f38"
    - "#829b85"
    - "#a7b499"
    - "#f2f0d3"
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
