analytics: {}
color:
  brandColors:
    - '#fffcad'
    - '#6a1395'
    - '#9b609d'
    - '#d3b7a6'
    - '#ff00ff'
  brandStrength: 0.5
  lightness: 0.4375
  rhythmicContrast: 0.75
  saturation: 1
cta: {}
layout_spectrum: 0.384009
name: Random Shit From The Internet
opengraph: {}
purpose: []
typography_spectrum: 0.30983
