typography_spectrum: 0.30983
color:
  brandColors:
    - '#fffcad'
    - '#6a1395'
    - '#9b609d'
    - '#d3b7a6'
    - '#ff00ff'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.70622
analytics:
  google: null
  facebook: null
  twitter: null
name: Random shit from the web
cta:
  domain: null
  bucket: null
  version: null
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/3e43047a-2523-4ab3-8737-ad52c27defb2.jpg'
purpose: []
