name: Random Shit From The Internet
style: A1
favicon: null
layout_spectrum: 0.8
typography_spectrum: "0.5"
title: Random Shit From The Internet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - "#6c7080"
    - "#ffa426"
    - "#93b6dd"
    - "#4d0100"
    - "#f4ffff"
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
