title: Silliness Galore
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3125
  brandStrength: 0
  rhythmicContrast: 0.25
  brandColors:
    - '#fffcad'
    - '#6a1395'
    - '#9b609d'
    - '#d3b7a6'
    - '#ff00ff'
  lightness: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f7983e78-f181-4d66-a588-15ca98e56a7a.jpg
author:
  name: Moritz Krog
  email: moritzkrog@gmail.com
  url: 'https://plus.google.com/+MoritzKrog'
name: Random shit from the web
opengraph:
  image: null
  type: ''
  appId: ''
typography_spectrum: 0.6787521
layout_spectrum: 0.5177066
content_rating:
  adult: false
