name: Random Shit From The Internet
favicon: null
layout_spectrum: 0.76848
typography_spectrum: 0.20576
style: taylor
title: Random Shit From The Internet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffcad'
    - '#6a1395'
    - '#9b609d'
    - '#d3b7a6'
    - '#ff00ff'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
