name: Random Shit From The Internet
favicon: null
layout_spectrum: 1
typography_spectrum: 0.30983
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffcad'
    - '#6a1395'
    - '#9b609d'
    - '#d3b7a6'
    - '#ff00ff'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
